<?php echo $this->doctype();

?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/responsive.css')) 
//                        ->prependStylesheet($this->basePath('css/style_front.css')) 
                        ->prependStylesheet($this->basePath('css/style.css')) 
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) 
                        ->prependStylesheet($this->basePath('css/font-awesome.css')) 
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) 
                ?>

                <!-- Scripts -->
        <?php echo $this->headScript()
//            ->prependFile($this->basePath('js/main.js'))
//            ->prependFile($this->basePath('js/wow.min.js'))
//            ->prependFile($this->basePath('js/jquery.isotope.min.js'))
//            ->prependFile($this->basePath('js/jquery.prettyPhoto.js'))
//            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
//            ->prependFile($this->basePath('js/jquery-1.10.2.js'))
//            ->prependFile($this->basePath('js/bootstrap.js'))
        ; ?>

    </head>
    
    <body>
      
        <!--<div class="">-->
            <?php echo $this->content; ?>
            <hr>
<!--            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>-->
        <!--</div>  /container -->
        
        <?php echo $this->inlineScript() ?>
      
                
<footer id="footer" class="midnight-blue">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <?php echo date('Y') ?> Assignment Project.
<!--                        <div class="credits">
                            <a href="https://bootstrapmade.com/"></a> by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                        </div>-->
                    </div>
                    
                </div>
            </div>
        </footer><!--/#footer-->
    </body>
</html>
