


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php
$title = 'Add Question';
$this->headTitle($title);
?>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
</head>

<body>
     <?php
    $form = $this->form;


    $form->prepare();

    echo $this->form()->openTag($form) . "<br>";
    //echo $this->formHidden($form->get('paymentid')) . "<br>";
    ?>
<div id="Wrapper">
    
<div class="container m-t-20 m-b-20 ">

<div class="row">
<div class="col-lg-8 col-lg-offset-2">
<div class="GreyBgColor img-rounded p-10">

<div class="row">
<div class="col-lg-12">
<div class="BluekBgColor p-10 FontSize18 WhiteTextColor text-center"><b><a href="<?php echo $this->url('assignment/default', array('controller' => 'index', 'action' => 'addassignment')); ?>">ADD NEW CALL</a></b></div>
<div class="col-sm-6 pull-right"> 
                <div class="addUserBtn"></div>
            </div>
</div>
</div>



<div class="row m-t-10" id="addque">
<div class="col-lg-12">
<!--<div class="BorderBox img-rounded p-10">
Add your question here
</div>-->
<div id="clone" class="clone">
    <div>
        <?php
        echo $this->formRow($form->get('question1'));
        ?>
<!--        <select class="" name="txtCategory[]" id="question1">
            <option value="">Please select</option>
        </select>-->
    </div>
   <div class="col-sm-3 plusminus"><h3><a href="javascript:void(0)" class="BlackColor"><span class="glyphicon glyphicon-plus-sign add" id="add"></span></a> <a href="javascript:void(0)" class="BlackColor"><span class="glyphicon glyphicon-minus-sign minus"></span></a></h3></div>
   
<!--    <div class="actions">
        <div class="clone badge GreenBgColor"><i class="fa fa-plus" ></i></div> 
        <button class="remove badge GreenBgColor"><i class="fa fa-minus" ></i></button>
    </div>-->
</div>
 
</div>
</div>



<div class="row m-t-10">
<div class="col-lg-12 " id="newclone"></div>
<!--<div class="col-lg-4 col-sm-4" >-->
<!--<span id="plus" class="badge GreenBgColor"><i class="fa fa-plus" ></i></span> Add New Question-->
<!--</div>-->
</div>


<div class="row m-t-20">
<div class="col-lg-12">
<!--<button type="button" class="btn btn-primary">Save</button>
<button type="button" class="btn btn-default">Cancel</button>-->
 <?php
    echo $this->formInput($form->get('submit'))."    ";
    
     echo $this->formInput($form->get('cancel')) . "<br>";
    echo $this->form()->closeTag($form) . "<br>";
    ?> 
</div>
</div>


</div>
</div>
</div>

</div>
   
</div>
    
</body>
</html>

<!--<script> 
    var cloneCount = 1;;
   $("#plus").click(function(){
      $('#addque')
          .clone()
          .attr('addque', 'addque'+ cloneCount++)
          .insertAfter($('[addque^=addque]:last'))
          .text('addque ' + (cloneCount-1)); //<--For DEMO
   }); 
</script>-->
<script>
var regex = /^(.+?)(\d+)$/i;
var cloneIndex = $(".clonedInput").length;

function clone(){
    $(this).parents(".clonedInput").clone()
        .appendTo("#newclone")
        .attr("id", "clonedInput" +  cloneIndex)
        .find("*")
        .each(function() {
            var id = this.id || "";
            var match = id.match(regex) || [];
            if (match.length == 3) {
                this.id = match[1] + (cloneIndex);
            }
        })
        .on('click', 'button.clone', clone)
        .on('click', 'button.remove', remove);
    cloneIndex++;
}
function remove(){
    $(this).parents(".clonedInput").remove();
}
$("button.clone").on("click", clone);
if(cloneIndex>1){
    $("button.remove").on("click", remove);
    }
   
</script>
